### ISSUE TITLE
PHP Warning:  Undefined property: ddnotes_model::$tablename

### ISSUE THREAD

**Issue by asd014** [dondominio/ddnotes#10]
Hello,

After updating with the new version 1.0.4, got another warning:
`PHP Warning:  Undefined property: ddnotes_model::$tablename in \...path\roundcubemail-1.5.3\plugins\ddnotes\includes\ddnotes_model.php on line 553`

**Comment by JAndreuSoler** [comment]
hi,

This bug and others like it should be fixed in the new version v1.0.5, thanks for the report.
