### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by HostOncilla** [dondominio/ddnotes#11]
When switching to dark mode, css isn't changing everything to display in dark mode.

**Comment by JAndreuSoler** [comment]
Hi, the dark mode issue should be fixed in the last version.
Thanks for the report!

**Comment by HostOncilla** [comment]
hi, the date and size elements don't display correctly on dark mode. Something like this needs to be added.

`html.dark-mode .ddnotes_list_element_date, html.dark-mode .ddnotes_list_element_size {color: #8ba3a7;}`
