### ISSUE TITLE
Installing under PHP 8.1

### ISSUE THREAD

**Issue by toteph42** [dondominio/ddnotes#12]
Hi,
when installing this plugin in an fresh installation, but existing mysql database, then composer installation fails:

` ERROR: [1050] Table 'ddnotes' already exists (SQL Query: CREATE TABLE 'ddnotes' (`

Found in RoundCobe 1.6.1 and ddnotes 1.0.6.

**Comment by JAndreuSoler** [comment]
Hi,
this issue is fixed for MySQL, PostgreSQL and SQLite in the version 1.0.7, if you have a different database you will have to export the data to import it once the table is created again.

Thanks for the report!
