### ISSUE TITLE
roundcube 1.4.13

### ISSUE THREAD

**Issue by GreySdz** [dondominio/ddnotes#8]
MySQL: 5.5.5-10.3.31-MariaDB-0+deb10u1 с MySQLi

when creating a database
(1005): Can't create table `dbnotes`.`ddnotes` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by JAndreuSoler** [comment]
It looks like a problem with the format of `user_id`, can you check that the format of `user_id` inside the `users` table is `INT(10) UNSIGNED NOT NULL`?

**Comment by JAndreuSoler** [comment]
Can you also check that you are running the `CREATE TABLE` on the roundcube database?

**Comment by GreySdz** [comment]
Hi.
where in the roundcube to look for the notes button

**Comment by JAndreuSoler** [comment]
In the Eastic skin it appears in the side menu on the left and in the Larry skin in the top menu
