### ISSUE TITLE
HP Warning:  Undefined array key "ddnotes_id"

### ISSUE THREAD

**Issue by asd014** [dondominio/ddnotes#9]
Hi, 

Trying to enable this plugin and got an error 
`PHP Warning:  Undefined array key "ddnotes_id" in path..\roundcubemail-1.5.3\plugins\ddnotes\ddnotes.php on line 561`

**Comment by JAndreuSoler** [comment]
Hi @asd014 ,

This error should be fixed in new release v1.0.5, thanks for the report.
